### ISSUE TITLE
Instale el modulo de TODO en la version 1.7.6

### ISSUE THREAD

**Issue by pekin10** [TodoPago/Plugin-PrestaShop#40]
Mi problema en un principio era la version de PHP tenia la version 5.6 No me andaba sin querer sin mucho conocimiento actualice a la version 7.1 y me andaba perfecto de repente en el servidor desaparece la version 7.1 y ponen la 7.0-7.2 y 7.3  de ahi en mas me dio siempre habla con el HOSTING y le dije q me pongo el PHP 7.1 veo q me lo puso rapido pero ahora no me anda mas no se q hacer!!!!!!

                                            Esta página no funciona
La página computationalcenter.com.ar no puede procesar esta solicitud ahora.
                                                HTTP ERROR 500

# PrestaShop-plugin | Issue Técnico
> Poner un problema en su respectivo contexto acelera su resolución. </br>
Esta guía tiene como objetivo contextualizar el inconveniente desde un primer momento.

> __Para consultas acerca de nuevas funcionalidades o información comercial utiliza el formulario de contacto de www.todopago.com.ar__

## Requisitos

* [ ] ¿Habilitaste la extensión SOAP de PHP?
* [ ] ¿Habilitaste la extensión CURL de PHP?
* [ ] ¿Habilitaste la extensión openSSL de PHP?
* [ ] ¿Seguiste los pasos de instalación descritos en [README.md](https://github.com/TodoPago/Plugin-PrestaShop/blob/master/README.md)?
* [x] Completar con una X dentro de los corchetes para los requisitos cumplidos.

## Comportamiento esperado
> Describinos qué respuesta se espera.

## Comportamiento actual
> Describinos qué está sucediendo actualmente.

## Pasos a reproducir
> Contanos, con el mayor detalle posible, qué pasos realizar para replicar el error.

## Entorno
> Completar con las versiones de las distintas herramientas aplicadas.
+ Entorno
  * __SO:__
  * __Servidor Web y versión:__
  * __Versión de PHP:__ _De ser posible, link a phpinfo()_
  * __Versión de PrestaShop:__
  * __Versión de TodoPago:__
  * __Ambiente de Todopago:__

## Comentario
> Cualquier cosa que quieras comentas que consideres pueda aportar a la detección y resolución del problema.

**Comment by curcio79** [comment]
@pekin10 buenos dias, la version actual de plugin llega hasta el 1.6 por los cambios q implemento prestashop. Estamos trabajando en una nueva version del plugin  para las nuevas versiones de presta. Si queres pasame mas info y lo vemos, dejo el ticket abierto esperando tu respuesta.
